---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dss
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dss
  template:
    metadata:
      labels:
        service: dss
    spec:
      containers:
        - name: dss
          image: interuss/dss:latest
          imagePullPolicy: IfNotPresent
          command: [ "core-service",
                     "-addr", ":8082",
                     "-public_key_files", "test-certs/auth2.pem",
                     "--cockroach_host", "cockroach.default.svc.cluster.local",
                     "-log_format", "console",
                     "-dump_requests",
                     "-accepted_jwt_audiences", "core-service,localhost",
                     "-enable_scd",
                     "-enable_http"
                    ]
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

      initContainers:
        - name: bootstraping-rid
          image: interuss/dss:latest
          imagePullPolicy: IfNotPresent
          command: [ "/usr/bin/db-manager" ]
          args: [ "--schemas_dir", "db-schemas/rid",
                  "--db_version", "latest",
                  "--cockroach_host", "cockroach.default.svc.cluster.local"
                ]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: bootstraping-scd
          image: interuss/dss:latest
          imagePullPolicy: IfNotPresent
          command: [ "/usr/bin/db-manager" ]
          args: [ "--schemas_dir", "db-schemas/rid",
                  "--db_version", "latest",
                  "--cockroach_host", "cockroach.default.svc.cluster.local"
                ]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
